### ISSUE TITLE
Fresh install does not run due to missing dependencies

### ISSUE THREAD

**Issue by marcesher** [cfpb/CFPBot#3]
It seems that either package.json or the README is incomplete.

`git clone`, then `npm install`, then `./bin/hubot` initially results in 

`Error: Cannot find module 'lodash'`

It seems either modules are missing from package.json, or it expects globally installed npm packages which aren't called out in the README

Or, as seems to be the preferred communication mechanism round this here repo: :rage:

**Comment by contolini** [comment]
:pensive: :hospital: :clock1:
